mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path("polls/", include("polls.urls"))
]

mysite/polls/urls.py
from django.urls import path

from . import views

app_name = "polls"

urlpatterns = [
    path("", views.index, name = "index"),
    #path("", views.IndexView.as_view(), name = "index"),
    path("<int:question_id>/", views.detail, name = "detail"),
    #path("<int:pk>/", views.DetailView.as_view(), name = "detail"),
    path("<int:question_id>/vote/", views.vote, name = "vote"),
    path("<int:question_id>/result/", views.result, name = "result"),
    # path("<int:question_id>/result/", views.ResultView.as_view(), name = "result"),

    #add new question
    path("new/", views.add_page, name = "add"),

    #edit choice
    path("<int:question_id>/edit_page/", views.edit_page, name = "edit_page"),
    path("add/", views.add_question, name = "add_question"),
    path("<int:choice_id>/delete_choice", views.delete_choice, name = "delete_choice"),
    path("<int:question_id>/edit_choice", views.edit_choice, name = "edit_choice"),
    path("<int:question_id>/add_choice", views.add_choice, name = "add_choice"),
    path("<int:question_id>/change_question", views.change_question, name = "change_question"),
    path("<int:question_id>/edit_question/", views.edit_question, name = "edit"),
]

mysite/polls/models.py
from django.db import models
from django.utils import timezone
import datetime


# Create your models here.

class Question(models.Model):
    question_text = models.TextField(max_length=100, unique=True)
    pub_date = models.DateTimeField("Date published")
    
    def __str__(self):
        return self.question_text
    
    def was_published_recently(self):
        return (self.pub_date >= timezone.now() - datetime.timedelta(days=1)) and (self.pub_date <= timezone.now())

    

class Choice(models.Model):
    choice_text = models.TextField(max_length=100)
    vote = models.IntegerField()
    question = models.ForeignKey(Question, on_delete = models.CASCADE)

    def __str__(self):
        return self.choice_text

mysite/polls/views.py
from django.shortcuts import render, get_object_or_404
from django.http import Http404, HttpResponseRedirect
from django.db.models import F
from django.urls import reverse
from django.utils import timezone
from django.views import generic

from .models import Question, Choice

#Create your views here.
def index(request):
    question_list = Question.objects.all()
    return render(request, "polls/index.html", 
                  {
                      "question_list" : question_list
                    })

# class IndexView(generic.ListView):
#     template_name = "polls/index.html"
#     context_object_name = "question_list"

#     def get_queryset(self):
#         return Question.objects.order_by('question_text', 'pub_date').distinct('question_text')


def detail(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    choices = question.choice_set.all()
    return render(request, "polls/detail.html", 
                  {
                      "choice_list" : choices,
                      "question" : question
                    })
# class DetailView(generic.DetailView):
#     model = Question
#     template_name = "polls/detail.html"

def vote(request, question_id):

    question = get_object_or_404(Question, pk=question_id)
    choices = question.choice_set.all()
    try:
        selected_choice = question.choice_set.get( pk=request.POST["choice"])
    

    except(KeyError, Choice.DoesNotExist):
        return render(request, "polls/detail.html", 
                {
                "question" : question,
                "choice_list" : choices
                })
                
    else:
        selected_choice.vote = F("vote") + 1
        selected_choice.save()

        return HttpResponseRedirect(reverse( "polls:result", args = (question.id,)))
        #The comma in args is important as it gives args value a list instead of a single value
        #Note: problem of implicit type conversion

def result(request, question_id):
    
    question = get_object_or_404(Question, pk=question_id)

    return render(request, "polls/result.html",
                  {
                      "question": question
                      })

# class ResultView(generic.DetailView):
#     model = Question

#     template_name = "polls/result.html"


def add_page(request):

    return render(request, "polls/add_question.html")

def add_question(request):
    #Todo:
    #url:ok
    #link with index:OK
    #form to post new question:Ok
    #choices for the question as well:ok
    #update the new question from result.POST to database:OK
    
    # try:
    q = Question(question_text = request.POST["question"], pub_date = timezone.now())
    # except(IntegrityError):

    q.save()
    print(q.id)
    # except: 

    return HttpResponseRedirect(reverse("polls:edit_choice", args = (q.id,)))

def edit_page(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    choices = question.choice_set.all()
    return render(request, "polls/edit_page.html", 
                  {
                      "choice_list" : choices,
                      "question" : question
                    })



def edit_question(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    question.delete()
    
    return HttpResponseRedirect(reverse( "polls:index"))

def change_question(request, question_id):
    pass

def delete_choice(request, choice_id):
    #Todo:
    #url-edit pass:ok
    choice = get_object_or_404(Choice, pk=choice_id)
    choice.delete()
    return HttpResponseRedirect(reverse( "polls:index"))


def edit_choice(request, question_id):
    question = get_object_or_404(Question, pk=question_id)

    return render(request, "polls/edit_choice.html", 
                  {
                      "question" : question
                    })

def add_choice(request, question_id):
    q = Question.objects.get(pk=question_id)
    q.choice_set.create(choice_text = request.POST["choice_text"], vote = 0)

    return HttpResponseRedirect(reverse("polls:edit_choice", args = (q.id,)))

mysite/polls/templates/polls/add_choice.html
{% extends "./base.html" %}

{% block title %}Add Choice{% endblock %}

{% block content %}

<h1>{{question.question_text}}</h1>
<ul>
    {% for c in question.choice_set.all %}
    <li>{{ c.choice_text }}</li>
</ul>
<h3> Add Choices </h3>

<form action = "{% url 'polls:add_choice'%}", method ="post">
    {%csrf_token %}

    <fieldset>
        <input type="text" id = "choice_text" name = "choice_text"><br>
        <label for = "choice_text"> Choice_text</label>
    </fieldset>

    <input type="submit" value="Submit">
    
</form>

{% endblock %}

mysite/polls/templates/polls/add_question.html
{% extends "./base.html" %}

{% block title %}Add Question{% endblock %}

{% block content %}

<h1> New Question </h1>

<form action = "{% url 'polls:add_question'%}" method ="post">
    {%csrf_token %}

    <fieldset>
        <input type="text" id = "question" name = "question"><br>
        <label for = "question"> Question_text</label>
    </fieldset>

    <input type="submit" value="Submit">
    
</form>

{% endblock %}

mysite/polls/templates/polls/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">

<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>{% block title %}Poll{% endblock %}</title>
</head>

<body>
        
    <div id="navbar">
        
        
        <div class="nav"> <a href="/polls">Home</a> </div>
        
        {% block navbar %}
        {% endblock %}
        <div style="margin-left: auto;" class="nav"> <a href="/logout">Logout</a> </div>
    </div>

    <div id="content">
        {% block content %}{% endblock %}
    </div>
</body>
</html>

mysite/polls/templates/polls/detail.html
{% extends "polls/base.html" %}


{% block title %}DETAIL{% endblock %}

{% block content %}

<form action="{% url 'polls:vote' question.id %}" method ="post">
{% csrf_token %}

<fieldset>
	<h1>{{ question.question_text }}</h1>
	{% for c in choice_list %}
		<input type="radio" id="choice{{ forloop.counter }}" name="choice" value="{{c.id}}">
		<label for="choice{{ forloop.counter }}">{{ c.choice_text }}"</label>
	{%endfor%}
</fieldset>

<input type="submit" value="Vote">	

</form>

{% endblock %}

mysite/polls/templates/polls/edit_choice.html
{% extends "./base.html" %}

{% block title %}Add Choice{% endblock %}

{% block content %}

<h1>{{question.question_text}}</h1>
<ul>
    {% for c in question.choice_set.all %}
    <li>{{ c.choice_text }}</li>
    {% endfor %}
</ul>
<h3> Add Choices </h3>

<form action = "{% url 'polls:add_choice' question.id%}", method ="post">
    {%csrf_token %}

    <fieldset>
        <input type="hidden" id = "question_id" name="question_id" value = "{{ question.id }}"><br>
        <input type="text" id = "choice_text" name = "choice_text"><br>
        <label for = "choice_text"> Choice_text</label>
    </fieldset>

    <input type="submit" value="Submit">
    
</form>

{% endblock %}

mysite/polls/templates/polls/edit_page.html
{% extends "./base.html" %}


{% block title %}Poll{% endblock %}

{% block content %}
<h2 style="margin-top: 30px;">
    Select the Choice to delete
</h2>
<ul style="margin-top: -10px;">
    {% for c in choice_list %}

        <li>
            <a href="{% url 'polls:delete_choice' c.id %}">{{ c.choice_text }}</a>
        </li>


    {% endfor %}
</ul>
<h3>
    <a href="{% url 'polls:edit_choice' question.id %}">Add new choice</a>
</h3>


{% endblock %}

mysite/polls/templates/polls/index.html
{% extends "./base.html" %}


{% block title %}Poll{% endblock %}

{% block navbar %}
        
        
        <div class="nav" id="add_q"> <a href="{% url 'polls:add' %}">Add Question</a></div>
        
        
{% endblock %}


{% block content %}
<div id="info">Click a question to vote</div>


<div id="title">
    <h1>Question List</h1>
</div>

{% for q in question_list %}

    <div id="qn">
        <ul>
            <li class="qn_t">
                <a  href="{% url 'polls:detail' q.id %}">{{ q.question_text }}</a>
            </li>
                
        </ul>
        <p style="font-size: 20px;">{{ q.pub_date }}</p>
        <div class="meta" >
            <a  href="{% url 'polls:edit_page' q.id %}">Edit question</a>
            <a style="float: right;" href="{% url 'polls:edit' q.id %}">Delete question</a>
        </div>
        
    </div>

{% endfor %}


{% endblock %}

mysite/polls/templates/polls/result.html
{% extends "./base.html" %}

{% block title %} "{{ question.question_text }}" {% endblock %}

{% block content %}
	
	<h1> "{{ question.question_text }}" </h1>
	<ul>
		<li><b> choices : votes</b> </li>
		
		{% for choice in question.choice_set.all %}
			<li> {{ choice.choice_text }} : {{ choice.vote }} </li>
		{% endfor %}
	</ul>
	
	
	<a href = "{% url 'polls:detail' question.id %}" >Cast another vote</a>
{% endblock %}